server:
  error:
    include-stacktrace: never
spring:
  application:
    name: votacao-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./data/db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  output:
    ansi:
      enabled: always
